exclude: ^src/third_party/libenjoy/
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        # Disable rule MD013: maximum line length 80 columns
        args: [ --disable=MD013 ]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint
        # Disable rule C0307: indentation width, because it does not match the default CLion indentation.
        args: [ --line-width=120, --disabled-codes=C0307 ]

  - repo: https://github.com/bufbuild/buf
    rev: b2393b4dd155690d51b284bc7504808b32e2998d
    hooks:
      - id: buf-lint
        args: [ "--config=proto/buf.yml" ]

  - repo: https://github.com/PyCQA/flake8
    rev: 88a4f9b2f48fc44b025a48fa6a8ac7cc89ef70e0
    hooks:
      - id: flake8
        # We need to ignore some errors in the blender addon, Flake8 gets confused about the bpy import
        args: [ "--max-line-length=120", "--per-file-ignores=tools/blender_exporter_addon/src/__init__.py:F722,F821" ]

  - repo: https://github.com/PyCQA/isort
    rev: c655831799765e9593989ee12faba13b6ca391a5
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 8fe627072f15ff2e3d380887b92f7868efaf6d05
    hooks:
      - id: black

  - repo: https://github.com/cpplint/cpplint
    rev: f4363d7fc0d5f38c4fd41b658e069e96583da0d5
    hooks:
      - id: cpplint
        # Disable the rules:
        # - build/c++11, I use modern C++ without restricting myself to subsets.
        # - build/c++17, same as above
        # - whitespace/indent_namespace, has a lot of false positives on continuation indents
        args: [ "--filter=-build/c++11,-build/c++17,-whitespace/indent_namespace", "--linelength=120" ]
